spring:
  security:
    user:
      name: user
      password: 123456
  datasource:
    url: jdbc:mysql://root:cQNkhVBiYEvlBMhhvozAdHajKVKqzFFT@junction.proxy.rlwy.net:29493/railway
    username: root
    password: cQNkhVBiYEvlBMhhvozAdHajKVKqzFFT
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 172800000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

frontend-url: http://localhost:5173

# CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dawqytffc
cloudinary:
  cloud-name: dawqytffc
  api-key: 233677167656433
  api-secret: 8kfFxYc6xPzaMM25boKVCESDpaE

# vnpay
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: M1K8IF92
    secretKey: BW8ZE1YP4ZAKCE1QAHEWS9INRYAE7Z71
    returnUrl: http://localhost:8080/api/payment/vnpay-callback

logging:
  level.org:
    springframework:
      security: DEBUG
      orm.jpa.JpaBaseConfiguration: ERROR
    hibernate:
      SQL: OFF
      type.descriptor.sql.BasicBinder: OFF
      orm.deprecation: ERROR
      engine.transaction.jta.platform.internal.JtaPlatformInitiator: ERROR

server:
  port: 8080